spring.application.name=JustDoItCloudPresentacion
spring.web.locale=es_CR
spring.web.locale-resolver=fixed

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

spring.datasource.url=jdbc:h2:mem:justdoitdb;MODE=MySQL;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true

internal.archiverBaseUrl=http://localhost:8090/api/v1/archives
